### ISSUE TITLE
Add systemd-journald watcher

### ISSUE THREAD

**Issue by r-darwish** [Ralvke/logram#1]

**Comment by mxseev** [comment]
Hi. 
I thought about this feature
Probably will, after full rewrite
During the week

**Comment by r-darwish** [comment]
I think I'm able to do it. If you tend to rewrite the project then maybe I should wait.

**Comment by mxseev** [comment]
Hi. Sorry for a late response
I made limited journald support (only for systemd units). If you need full support let me know
Please try and give feedback
Happy new year

**Comment by r-darwish** [comment]
I actually forgot about it. I'll take a look

**Comment by mxseev** [comment]
Closing due inactivity.
Feel free to create new issue if you have any problems with this feature.
