### ISSUE TITLE
Make it possible to use it as a log-logger?

### ISSUE THREAD

**Issue by jens1o** [Ralvke/logram#2]
So we can simply add it as the logger for  https://crates.io/crates/log ?

**Comment by mxseev** [comment]
At the moment there is support for `slog`
https://github.com/Ralvke/logram#use-logram-as-slog-drain

But i have plans for fully rewrite logram, and i add support for `log`
I plan to do this in a week.

**Comment by jens1o** [comment]
Cool! Thanks!

**Comment by mxseev** [comment]
Hi. Sorry for a late response
I made it, https://github.com/Ralvke/logram#usage-with-log
Please try and give feedback
Happy new year

**Comment by jens1o** [comment]
No worries, I'm aware of being a maintainer with limited resources in terms of time. :)

I'll test it tomorrow in the new year :tada:

**Comment by jens1o** [comment]
Works perfectly fine, thank you! :)

**Comment by mxseev** [comment]
Update: log records with target starts with `tokio_reactor, hyper, mio, want or reqwest` will be skipped, because limitations in `log` #https://github.com/rust-lang-nursery/log/issues/312
