### ISSUE TITLE
Unable to run cargo test on Windows 10

### ISSUE THREAD

**Issue by incker2** [Ralvke/logram#4]
Unable to run `cargo test` on Windows 10:

    error: failed to run custom build command for `libsystemd-sys v0.2.2`

    Caused by:
      process didn't exit successfully: `C:\dev\pr\logram\target\debug\build\libsystemd-sys-ebc25a8bfa53dc04\build-script-build` (exit code: 101)
    --- stdout
    Failed to run `"pkg-config" "--libs" "--cflags" "libsystemd"`: The system cannot find the file specified. (os error 2)

    --- stderr
    thread 'main' panicked at 'systemd was not found via pkg-config nor via the env var LIBSYSTEMD_LDFLAGS', C:\Users\iamlo\.cargo\registry\src\github.com-1ecc6299db9ec823\libsystemd-sys-0.2.2\build.rs:19:13
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by mxseev** [comment]
Unfortunately I can not fix it now, because I do not have access to the
desktop. I will be available in December.

Sorry for the late reply.

ср, 22 янв. 2020 г., 22:54 incker2 <notifications@github.com>:

**Comment by mxseev** [comment]
Hello again. I finally have access to a computer and can do real work. 
logram has been rewritten from scratch in v.2.0, and now you can disable journald log source building in Windows, e.g. `cargo build --release --features=bin_core,ls_filesystem`. More info see at [Building section in README](https://github.com/mxseev/logram#building)
